services:
  postgres:
    image: postgres:16-alpine
    container_name: savemysnippets_postgres
    environment:
      POSTGRES_USER: savemysnippets_admin
      POSTGRES_PASSWORD: savemysnippets_admin
      POSTGRES_DB: savemysnippets_db
    ports:
      - "5433:5432"
    volumes:
      - savemysnippets_postgres_data:/var/lib/postgresql/data
    networks:
      - savemysnippets_network
    healthcheck:
      test:
        ["CMD-SHELL", "pg_isready -U savemysnippets_admin -d savemysnippets_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: savemysnippets_server
    env_file:
      - ./server/.env.production
    environment:
      DJANGO_DEBUG: True
      DJANGO_SECRET_KEY: ynejknviqenurc638743c7nr2hf7tc3r78t1b83
      POSTGRES_DB: savemysnippets_db
      POSTGRES_USER: savemysnippets_admin
      POSTGRES_PASSWORD: savemysnippets_admin
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    ports:
      - "8000:8000"
    networks:
      - savemysnippets_network
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  savemysnippets_postgres_data:

networks:
  savemysnippets_network:
    driver: bridge
